// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD4I4koIV2CINgSG24370oRu8LKlOqF0GU',
//     appId: '1:155504144686:android:72eb612ffd80d424c5cabf',
//     messagingSenderId: '155504144686',
//     projectId: 'project1-527a7',
//     databaseURL: 'https://project1-527a7-default-rtdb.asia-southeast1.firebasedatabase.app/',
//     storageBucket: 'project1-527a7.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBvzg1MQJaX2k84U95joZIC1vWfcndPl_k',
//     appId: '1:155504144686:ios:9b980fe92e35d48cc5cabf',
//     messagingSenderId: '155504144686',
//     projectId: 'project1-527a7',
//     storageBucket: 'project1-527a7.appspot.com',
//     iosClientId: '155504144686-krahvlgn2foasck6vf5mr1t1u4n57l3e.apps.googleusercontent.com',
//     iosBundleId: 'com.example.projectben',
//   );
// }
class ProFirebaseOptions{
  static const FirebaseOptions current = FirebaseOptions(
      apiKey: 'AIzaSyD4I4koIV2CINgSG24370oRu8LKlOqF0GU',
      appId: '1:155504144686:android:72eb612ffd80d424c5cabf',
      messagingSenderId: '155504144686',
      projectId: 'project1-527a7',
      databaseURL: 'https://project1-527a7-default-rtdb.asia-southeast1.firebasedatabase.app/',
      storageBucket: 'project1-527a7.appspot.com',
  );
}